"""added org constraints

Revision ID: 0d459513d50e
Revises: a77f796d21e2
Create Date: 2026-01-14 21:14:04.781536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d459513d50e'
down_revision: Union[str, Sequence[str], None] = 'a77f796d21e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'athletes', 'event_groups', ['event_group_id'], ['event_group_id'])
    op.create_foreign_key(None, 'athletes', 'teams', ['team_id'], ['team_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'athletes', type_='foreignkey')
    op.drop_constraint(None, 'athletes', type_='foreignkey')
    # ### end Alembic commands ###
