"""add season_id to meets

Revision ID: 62b8443802df
Revises: 5d855b72d4b8
Create Date: 2026-01-14 17:00:30.828380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b8443802df'
down_revision: Union[str, Sequence[str], None] = '5d855b72d4b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('seasons',
    # sa.Column('season_id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=80), nullable=False),
    # sa.Column('year', sa.Integer(), nullable=False),
    # sa.Column('discipline', sa.String(length=20), nullable=False),
    # sa.PrimaryKeyConstraint('season_id')
    # )
    # op.add_column('meets', sa.Column('season_id', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'meets', 'seasons', ['season_id'], ['season_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'meets', type_='foreignkey')
    # op.drop_column('meets', 'season_id')
    # op.drop_table('seasons')
    # ### end Alembic commands ###
