"""added season constraint

Revision ID: 8373009379fd
Revises: e9ddf699979d
Create Date: 2026-01-14 20:24:31.534859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8373009379fd'
down_revision: Union[str, Sequence[str], None] = 'e9ddf699979d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_season_name_year_disc', 'seasons', ['year', 'discipline', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_season_name_year_disc', 'seasons', type_='unique')
    # ### end Alembic commands ###
