"""edited model for org and cleanup

Revision ID: a77f796d21e2
Revises: 6442e52f22c2
Create Date: 2026-01-14 20:46:37.493170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77f796d21e2'
down_revision: Union[str, Sequence[str], None] = '6442e52f22c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_athletes_org_id'), 'athletes', ['org_id'], unique=False)
    op.create_foreign_key(None, 'athletes', 'organizations', ['org_id'], ['org_id'])
    op.create_foreign_key(None, 'meets', 'organizations', ['org_id'], ['org_id'])
    op.create_foreign_key(None, 'teams', 'organizations', ['org_id'], ['org_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_constraint(None, 'meets', type_='foreignkey')
    op.drop_constraint(None, 'athletes', type_='foreignkey')
    op.drop_index(op.f('ix_athletes_org_id'), table_name='athletes')
    # ### end Alembic commands ###
