"""initial schema

Revision ID: e9ddf699979d
Revises: 62b8443802df
Create Date: 2026-01-14 19:21:56.901901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9ddf699979d'
down_revision: Union[str, Sequence[str], None] = '62b8443802df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athletes',
    sa.Column('athlete_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('event_group_id', sa.Integer(), nullable=False),
    sa.Column('varsity', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('unavailable', sa.Boolean(), nullable=False),
    sa.Column('expected_return', sa.String(length=10), nullable=True),
    sa.Column('grad_year', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('athlete_id')
    )
    op.create_table('event_groups',
    sa.Column('event_group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('event_group_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('organizations',
    sa.Column('org_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('org_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('seasons',
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('discipline', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('season_id')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_index(op.f('ix_teams_org_id'), 'teams', ['org_id'], unique=False)
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_group_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=10), nullable=False),
    sa.Column('venue_type', sa.String(length=10), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_group_id'], ['event_groups.event_group_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('meets',
    sa.Column('meet_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('meet_date', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('is_varsity', sa.Boolean(), nullable=False),
    sa.Column('venue_type', sa.String(length=10), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.PrimaryKeyConstraint('meet_id')
    )
    op.create_index(op.f('ix_meets_org_id'), 'meets', ['org_id'], unique=False)
    op.create_table('meet_events',
    sa.Column('meet_event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meet_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('max_entries', sa.Integer(), nullable=True),
    sa.Column('is_scored', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['meet_id'], ['meets.meet_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meet_event_id'),
    sa.UniqueConstraint('meet_id', 'event_id', 'gender', name='uq_meet_event')
    )
    op.create_index(op.f('ix_meet_events_event_id'), 'meet_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_meet_events_meet_id'), 'meet_events', ['meet_id'], unique=False)
    op.create_table('meet_entries',
    sa.Column('meet_entry_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meet_event_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('entry_status', sa.String(length=12), nullable=False),
    sa.Column('seed_time', sa.String(length=20), nullable=True),
    sa.Column('seed_mark', sa.String(length=20), nullable=True),
    sa.Column('heat', sa.Integer(), nullable=True),
    sa.Column('lane', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.athlete_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meet_event_id'], ['meet_events.meet_event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meet_entry_id'),
    sa.UniqueConstraint('meet_event_id', 'athlete_id', name='uq_meet_entry')
    )
    op.create_index(op.f('ix_meet_entries_athlete_id'), 'meet_entries', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_meet_entries_meet_event_id'), 'meet_entries', ['meet_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meet_entries_meet_event_id'), table_name='meet_entries')
    op.drop_index(op.f('ix_meet_entries_athlete_id'), table_name='meet_entries')
    op.drop_table('meet_entries')
    op.drop_index(op.f('ix_meet_events_meet_id'), table_name='meet_events')
    op.drop_index(op.f('ix_meet_events_event_id'), table_name='meet_events')
    op.drop_table('meet_events')
    op.drop_index(op.f('ix_meets_org_id'), table_name='meets')
    op.drop_table('meets')
    op.drop_table('events')
    op.drop_index(op.f('ix_teams_org_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('seasons')
    op.drop_table('organizations')
    op.drop_table('event_groups')
    op.drop_table('athletes')
    # ### end Alembic commands ###
